# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ef56ba04aeffc51a4b08923a69aa5923e8a60916c0d44dd2118587b13caeb389ce2d61f197ca53374ef809023a7903f3db59d6c40f4cc38b96fe2f145436257

test:
  secret_key_base: 6870b1b72d6fda9c36cadbb41614d869e75990137c203b6c529d817609373a8da62db12698f0ab9781f1c218d902f75e5d2aa4c40304e7378bf8ef72bb6bcc0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
